=== BeilFerrer/Tasques-LMG/Practica_XML/4-1.dtd
<!ELEMENT cataleg (single | album)+>

<!ELEMENT single (titol, descripcio?, pais, idioma, genere*, grup, membres, durada)>
<!ATTLIST single codi CDATA #REQUIRED>

<!ELEMENT album (titol, descripcio?, pais, idioma, genere*, grup, membres, numero_canco, titols_cancos)>
<!ATTLIST album codi CDATA #REQUIRED>

<!ELEMENT titol (#PCDATA)>
<!ELEMENT descripcio (#PCDATA)>
<!ELEMENT pais (#PCDATA)>
<!ELEMENT idioma (#PCDATA)>

<!ELEMENT genere (Música_clásica |Jazz |Blues |Góspel |Soul |Pop |Rock_and_Roll |Country)>
<!ELEMENT Música_clásica EMPTY>
<!ELEMENT Jazz EMPTY>
<!ELEMENT Blues EMPTY>
<!ELEMENT Góspel EMPTY>
<!ELEMENT Soul EMPTY>
<!ELEMENT Pop EMPTY>
<!ELEMENT Rock_and_Roll EMPTY>
<!ELEMENT Country EMPTY>

<!ELEMENT grup (#PCDATA)>
<!ELEMENT membres (membre+)>
<!ELEMENT membre (nom)>
<!ATTLIST membre sexe (home | dona) #REQUIRED>
<!ELEMENT nom (#PCDATA)>

<!ELEMENT durada (#PCDATA)>

<!ELEMENT numero_canco (#PCDATA)>
<!ELEMENT titols_cancos (canco+)>
<!ELEMENT canco (titol_canco, durada_canco)>
<!ATTLIST canco numero CDATA #REQUIRED>
<!ELEMENT titol_canco (#PCDATA)>
<!ELEMENT durada_canco (#PCDATA)>

=== BeilFerrer/Tasques-LMG/Practica_XML/4-1XML.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cataleg SYSTEM "4-1.dtd">
<cataleg>
    <single codi="S001">
        <titol>Imagine</titol>
        <descripcio>Cançó clàssica de John Lennon</descripcio>
        <pais>Regne Unit</pais>
        <idioma>Anglès</idioma>
        <genere> <Pop/></genere>
        <genere> <Rock_and_Roll/></genere>
        <grup>The Beatles</grup>
        <membres>
            <membre sexe="home">
                <nom>John Lennon</nom>
            </membre>
            <membre sexe="home">
                <nom>Paul McCartney</nom>
            </membre>
        </membres>
        <durada>3:05</durada>
    </single>

    <album codi="A001">
        <titol>Abbey Road</titol>
        <pais>Regne Unit</pais>
        <idioma>Anglès</idioma>
        <genere><Rock_and_Roll/></genere>
        <grup>The Beatles</grup>
        <membres>
            <membre sexe="home">
                <nom>John Lennon</nom>
            </membre>
            <membre sexe="home">
                <nom>Paul McCartney</nom>
            </membre>
        </membres>
        <numero_canco>2</numero_canco>
        <titols_cancos>
            <canco numero="1">
                <titol_canco>Come Together</titol_canco>
                <durada_canco>4:19</durada_canco>
            </canco>
            <canco numero="2">
                <titol_canco>Something</titol_canco>
                <durada_canco>3:03</durada_canco>
            </canco>
        </titols_cancos>
    </album>
</cataleg>
